### PR TITLE
add viewport meta data

### LINKED ISSUE #48: Responsive design not working on iPhone 6S
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Responsive design not working on iPhone 6S, shows tiny desktop layout

**- If the current behavior is a bug, please provide the steps to reproduce.**
Open iOS Safari browser on iPhone 6S
Type in ‘netlifystatus.com’ (or any other Status Kit powered status pages)

**- What is the expected behavior?**
Responsive design that resized to accommodate the screen resolution as displayed on Android devices

**- Please mention your node.js, and operating system version.**
iOS 11.2.5 (latest)

### PR DESCRIPTION
**Pull request by steveoh**
closes #48

**- Summary**
Add the meta tag so the page doesn't shrink and can be responsive.

**- Test plan**
view it on our fork http://agrc-status.netlify.com/

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by steveoh** [comment]
@verythorough this is a simple one

**Comment by verythorough** [comment]
@steveoh Nice catch! I can't believe it wasn't in there before.

It should be in the `<head>`, though. Could you move it? I think after the `<title>` would be a good spot.

**Comment by steveoh** [comment]
@verythorough dun

**Comment by verythorough** [comment]
LGTM!

**Pull request merged**
